// Builds crates/wenmar-open-wasm for WebAssembly and puts it in dist/offline/
// twice: as the file `wenmar-open/offline.wasm` names, and as base64 text
// in a module, for every runtime that can compile bytes.
//
// It needs cargo and the wasm32-unknown-unknown target, which rustup
// installs from rust-toolchain.toml. Nothing is downloaded by this script.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = new URL("../../../", import.meta.url);
const out = new URL("../dist/offline/", import.meta.url);

// A panic message names the source file it came from. Without these, the
// file would carry the paths of whoever built it.
const remap = [
  [process.env.CARGO_HOME ?? join(homedir(), ".cargo"), "/cargo"],
  [process.env.RUSTUP_HOME ?? join(homedir(), ".rustup"), "/rustup"],
  [fileURLToPath(root).replace(/\/$/, ""), "/wenmar-open"],
];
const flags = remap.map(([from, to]) => `--remap-path-prefix=${from}=${to}`);

try {
  execFileSync(
    "cargo",
    ["build", "--locked", "-p", "wenmar-open-wasm", "--lib", "--target", "wasm32-unknown-unknown", "--profile", "wasm"],
    {
      cwd: root,
      stdio: "inherit",
      env: { ...process.env, CARGO_INCREMENTAL: "0", CARGO_ENCODED_RUSTFLAGS: flags.join("\u001f") },
    },
  );
} catch {
  console.error(
    "\nThe WebAssembly build failed. It needs the Rust toolchain of rust-toolchain.toml with the\n" +
      "wasm32-unknown-unknown target: run `rustup toolchain install` in the repository root.",
  );
  process.exit(1);
}

const wasm = readFileSync(new URL("target/wasm32-unknown-unknown/wasm/wenmar_open_wasm.wasm", root));
mkdirSync(out, { recursive: true });
writeFileSync(new URL("wenmar_open.wasm", out), wasm);
writeFileSync(
  new URL("wasm-inline.js", out),
  `// Generated by scripts/build-wasm.mjs: wenmar_open.wasm as base64.\nexport const WASM_BASE64 = "${wasm.toString("base64")}";\n`,
);
console.log(`dist/offline/wenmar_open.wasm: ${wasm.length} bytes`);
