[workspace]
resolver = "3"
members = ["crates/wenmar-vin", "crates/wenmar-vehicles", "crates/open-data"]

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT"
repository = "https://github.com/wenmar-pro/wenmar-open"
homepage = "https://open.wenmarpro.com"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
